/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TELAS;

import BEANS.LoginBean;
import DAO.LoginDao;
import java.sql.ResultSet;
import TELAS.Mapa_1_marcador;
/**
 *
 * @author eduar
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        senha = new javax.swing.JLabel();
        senhaCampo = new javax.swing.JPasswordField();
        border_senha = new javax.swing.JPanel();
        email = new javax.swing.JLabel();
        loginCampo = new javax.swing.JTextField();
        entrar = new javax.swing.JButton();
        border_email = new javax.swing.JPanel();
        entrar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(226, 226, 226));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(500, 640));
        getContentPane().setLayout(null);

        logo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        logo.setText("MotiON");
        getContentPane().add(logo);
        logo.setBounds(179, 66, 86, 38);

        senha.setText("Senha:");
        getContentPane().add(senha);
        senha.setBounds(40, 250, 48, 16);

        senhaCampo.setEditable(false);
        senhaCampo.setText("teste");
        senhaCampo.setBorder(null);
        senhaCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaCampoActionPerformed(evt);
            }
        });
        getContentPane().add(senhaCampo);
        senhaCampo.setBounds(90, 240, 320, 31);

        border_senha.setBackground(new java.awt.Color(105, 197, 103));

        javax.swing.GroupLayout border_senhaLayout = new javax.swing.GroupLayout(border_senha);
        border_senha.setLayout(border_senhaLayout);
        border_senhaLayout.setHorizontalGroup(
            border_senhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        border_senhaLayout.setVerticalGroup(
            border_senhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        getContentPane().add(border_senha);
        border_senha.setBounds(40, 270, 360, 3);

        email.setText("Email:");
        getContentPane().add(email);
        email.setBounds(40, 180, 48, 16);

        loginCampo.setEditable(false);
        loginCampo.setText("teste@teste.com");
        loginCampo.setBorder(null);
        loginCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginCampoActionPerformed(evt);
            }
        });
        getContentPane().add(loginCampo);
        loginCampo.setBounds(90, 170, 320, 32);

        entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGs/botao_login.png"))); // NOI18N
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });
        getContentPane().add(entrar);
        entrar.setBounds(30, 420, 90, 35);

        border_email.setBackground(new java.awt.Color(105, 197, 103));

        javax.swing.GroupLayout border_emailLayout = new javax.swing.GroupLayout(border_email);
        border_email.setLayout(border_emailLayout);
        border_emailLayout.setHorizontalGroup(
            border_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        border_emailLayout.setVerticalGroup(
            border_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        getContentPane().add(border_email);
        border_email.setBounds(40, 200, 360, 3);

        entrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMGs/botao_login.png"))); // NOI18N
        entrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(entrar1);
        entrar1.setBounds(321, 337, 87, 35);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        Mapa_1_marcador map = new Mapa_1_marcador(-23.51, -47.45);
    }//GEN-LAST:event_entrarActionPerformed

    private void senhaCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaCampoActionPerformed

    private void loginCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginCampoActionPerformed

    private void entrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel border_email;
    private javax.swing.JPanel border_senha;
    private javax.swing.JLabel email;
    private javax.swing.JButton entrar;
    private javax.swing.JButton entrar1;
    private javax.swing.JTextField loginCampo;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel senha;
    private javax.swing.JPasswordField senhaCampo;
    // End of variables declaration//GEN-END:variables
}
